

# 计算buildNumber
def updateProjectBuildNumber
    currentTime = Time.new.strftime("%m%d%H%M")
    build = "#{currentTime}"
    puts("*************| 更新build #{build} |*************")
    # => 更改项目 build 号
    increment_build_number(
        build_number: "#{build}"
    )
end

platform :ios do

  before_all do
  	# pod install
    	sh 'pod install'
    
	# 更新项目build号
        updateProjectBuildNumber
  end

	# 版本号
  	version = get_version_number(xcodeproj: "./RKCooperDemo.xcodeproj")

  	# git commit 号
	gitShortHash = last_git_commit[:abbreviated_commit_hash]

	# build号
  	currentTime = Time.new.strftime("%m%d%H%M")
  	

  desc "打Release 测试环境"
  lane :enterprise_test do

    ipaName = "RKCooperExample-#{version}-#{currentTime}-#{gitShortHash}-test.ipa"

    puts "包名: #{ipaName}".red

    gym(scheme: "RKCooperDemo",

        workspace: "RKCooperDemo.xcworkspace",

        include_bitcode: false,

        configuration: "Release",

        export_method: "enterprise",

        output_directory: "../build",

        output_name: "#{ipaName}",

        silent: false,

        include_symbols: true,

    )

   pgyer(api_key: "6d6e565738496299dfbbfe1219a7e2ed", user_key: "129fd9f7b6c1bba97d348232a6d5bd9c")

  end

  after_all do |lane|

  end

  error do |lane, exception|
    # slack(
    #   message: "Error message"
    # )
  end
end


